version: '3'

networks:
  an-over-engineered-blog:
    name: an-over-engineered-blog

services:
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    image: nginx
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      timeout: 5s
      retries: 5
    ports:
      - 80:80
    environment:
      NGINX_HOST: ${DOMAIN}
      NGINX_PORT: '80'
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - an-over-engineered-blog
    volumes:
      - ./.docker/config/nginx/templates:/etc/nginx/templates
      - ./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/public:/var/www/${SERVICE_NAME}/public

  php-fpm:
    build:
      context: .
      dockerfile: .docker/services/php/Dockerfile
      args:
        SERVICE_NAME: ${SERVICE_NAME}
        BUILD_ENV: ${BUILD_ENV}
    container_name: ${PROJECT_NAME}-${SERVICE_NAME}-microservice
    restart: unless-stopped
    volumes:
      - ./.docker/config/php/php.ini.development:/usr/local/etc/php.ini
      - ./app:/var/www/${SERVICE_NAME}
    networks:
      - an-over-engineered-blog
